global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: service-discovery
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8761"]

  - job_name: tenant-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: anomaly-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: telemetry-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: message-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: scheme-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8086"]

  - job_name: analytics-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]
